workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu;")


rule all:
    input:
        # qc
        "multiqc",
        "qc/panel-qc-summary.xlsx",
        # map
        expand("align/{sample}.bam.target.bedcov", sample=config["samples"]),
        # cnv
        expand("convading/{sample}/CreateFinalList", sample=config["samples"]),
        # allele & snp
        "report/allele.summary.tsv",
        expand("report/{sample}.summary.xlsx", sample=config["samples"]),


include: "rules/bed.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/map.smk"
include: "rules/summary.smk"
include: "rules/bqsr.smk"
include: "rules/convading.smk"
include: "rules/call.smk"
include: "rules/filter.smk"
include: "rules/allele.smk"
include: "rules/report_loci.smk"
