workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu;")


rule all:
    input:
        # qc
        "multiqc",
        "qc/panel-qc-summary.xlsx",
        # map
        expand("align/{sample}.bam.target.bedcov", sample=config["samples"]),
        # cnv
        expand("convading/{sample}/CreateFinalList", sample=config["samples"]),
        # allele & snp
        expand("report/{sample}.summary.xlsx", sample=config["samples"]),
        "report/all.diplotype_phenotype.tsv",
        # cyp2c19
        expand("cyp2c19/{sample}.summary.xlsx", sample=config["samples"]),
        "cyp2c19/all.diplotype_phenotype.tsv",


include: "rules/bed.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/map.smk"
include: "rules/summary.smk"
include: "rules/bqsr.smk"
include: "rules/convading.smk"
include: "rules/call.smk"
include: "rules/filter.smk"
include: "rules/allele.smk"
include: "rules/report.smk"
include: "rules/cyp2c19.smk"
