workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


rule all:
    input:
        "multiqc",
        "qc/panel-qc-summary.xlsx",
        expand("align/{sample}.bam.target.bedcov", sample=config["samples"]),
        "aldy/all-sample-snp.xlsx",
        "aldy/all-sample-genotype.xlsx",


include: "rules/prepare_ref.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/map.smk"
include: "rules/all_summary.smk"
include: "rules/aldy.smk"
